Side1
rusyonex/1st_website pull request #1
Opened 2020-08-08 18:26 UTC by rusyonex

Добавил белую полоску, не знаю правильно ли все сделал.

2020-08-08 18:38 UTC, Adamovskiy requested changes

2020-08-08 18:38 UTC, Adamovskiy commented on index.html
> +			<ul class="guide-flex"></ul>
Это, кажется, лишний элемент – между белой полоской и контентом.

2020-08-08 18:38 UTC, Adamovskiy commented on index.html
> +			</h1>
По умолчанию `h1` – строчный элемент. Здесь он превратился в блочный из-за использования `display: flex`. В принципе оно работает, но логически правильнее и просто удобнее структурировать блоками, а внутри блоков оборачивать строчки текста в строчные элементы. То есть конкретно здесь тебе надо поменять h1 и div местами.

Почитай вот тут:
https://webref.ru/course/html-basics/block-inline#:~:text=%D0%91%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D0%B5%20%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BD%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D1%8B%20%D0%B4%D0%BB%D1%8F%20%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F,%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82%20%D0%BE%D0%B4%D0%BD%D0%BE%20%D0%B8%D0%BB%D0%B8%20%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D1%81%D0%BB%D0%BE%D0%B2.

2020-08-08 18:38 UTC, Adamovskiy commented on index.html
> +		<div class="main_flex-container">
Если ты посмотришь в инспекторе, этот div не занимает всю высоту страницы, не смотря на наличие свойства `height: 100%`. Это происходит потому что свойство означает 100% от родительского элемента. 

У этого div-а два родительских элемента: `body` и `html`. Оба они работают как блочные элементы – по дефолту принимают минимальную  высоту чтобы вмещалось содержимое. Чтоб растянуть, им нужно тоже задать 100%.

2020-08-08 18:38 UTC, Adamovskiy commented on css/test.css
> +h1:before, h1:after {
Кажется это скопипасченные откуда-то лишние страшные штуки)

2020-08-08 18:46 UTC, rusyonex commented on css/test.css
> +h1:before, h1:after {
убрал

2020-08-08 20:12 UTC, rusyonex commented on index.html
> +		<div class="main_flex-container">
да, увидел, добавил нужные строчки.

2020-08-08 20:13 UTC, rusyonex commented on index.html
> +			</h1>
обсудили по телефону, поменял)

2020-08-08 20:21 UTC, rusyonex reviewed
исправил замечания, залил новый комит

2020-08-09 19:59 UTC, Adamovskiy requested changes

2020-08-09 19:59 UTC, Adamovskiy commented on css/test.css
> +    height: calc(100vh);
Как я и говорил, это чит, которым лучше не пользоваться без острой необходимости, всегда чем проще верстка тем лучше. Здесь чтобы добиться правильного поведения, нужно что-то вроде `calc(100vh - 216px)`, где 216 – суммарная высота всех хедеров. Просто 100vh у тебя делает всю страницу больше высоты окна браузера. В качестве проверки – когда элементы находятся в пределах окна, не появится вертикальный скролл.

Но более простое решение – просто указать этому элементу `flex-grow: 1` (и вынести его на один уровень выше, чтобы его родителем стал flex-контейнер).

Другой эффект, который вызвала слишком большая высота – белая линия пропала. Контент-контейнер как бы сжал её. Когда сделаешь высоту контейнера правильной, линия вернется.

2020-08-09 19:59 UTC, Adamovskiy commented on index.html
> +			<div>
Это лишняя вложенность, о которой написал в комменте выше.

2020-08-09 19:59 UTC, Adamovskiy commented on css/test.css
> +    width: 100%;
Здесь то же самое, ты задал ширину контента равной всей ширине окна браузера. Естественно в этом случае менюха и контент не влазят в их контейнер (который из-за флекса тоже шириной с браузер), и оба они равномерно ужимаются. В итоге и контент меньше 100%, и меню 212 пикселей вместо указанных 250. 

Здесь так же вместо этого нужно использовать `flex-grow: 1`.

Оффтопик: если бы сжатие было ожидаемым поведением, пропорции сжатия можно регулировать стилем `flex-shrink`.

2020-08-09 21:05 UTC, Adamovskiy approved these changes

2020-08-09 21:12 UTC, merged